### ISSUE TITLE
Support for TLS Missing

### ISSUE THREAD

**Issue by Inc8pable** [pupi1985/IPMonitor#11]
The JavaMail API supports TLS which is missing for sending mail through newer and popular email providers. When you get the time please add support for TLS for email notifications.

        // enable STARTTLS
        props.put("mail.smtp.starttls.enable", "true"); 

Thanks!
-Inc8pable

**Comment by pupi1985** [comment]
Added to [v0.6.0](https://github.com/pupi1985/IPMonitor/releases/tag/0.6.0)
