### ISSUE TITLE
Email notification content issue

### ISSUE THREAD

**Issue by remizik** [pupi1985/IPMonitor#15]
Hello,

I receive the email but with this content :(

![image](https://user-images.githubusercontent.com/24875086/41225173-842c0430-6d6e-11e8-96d9-7de17e164b8a.png)

here's my setup : 

![image](https://user-images.githubusercontent.com/24875086/41225121-63dbd53e-6d6e-11e8-9a2b-0dc451e952dc.png)

any idea ?
thanks

edit : %OLDIP% seems to work though..

**Comment by remizik** [comment]
any fix or workaround ?

**Comment by pupi1985** [comment]
https://github.com/pupi1985/IPMonitor/issues/4#issuecomment-277748592
