### ISSUE TITLE
Command to request URL fails with no error text

### ISSUE THREAD

**Issue by Ayelis** [pupi1985/IPMonitor#16]
I'm using Windows 10 Pro on my home server and I want to set up IP monitor to contact my DNS via their custom endpoint whenever my IP changes. I've got as far as installing the service and setting the timer, but when I try and test the curl command, it gives me an error. The error box that comes up, however, is completely empty.

I've tried the command in the console; it works fine. I've set IP monitor to use the same command on two lines, on one line, and with the full path to C:\Windows\System32\curl with the URL to access on the second line. No matter how I set it up, an error is reported, but the error window comes back empty.

**Steps to reproduce:**
1. Install and start IP Monitor as normal on Windows 10.
2. Register with a DNS service such as FreeDNS.
3. Set up your DNS subdomain and 'Enable Dynamic DNS' on your subdomain to get your dynamic update URL endpoint.
4. Change the options in IP Monitor in order to add a command.
5. Add the 'curl' command followed by the endpoint URL given by your DNS solution.
6. Press 'Test'.
7. Notice an error is reported, but the error message does not display.

**System Specs:**
GPU: Geforce GTX 960 2GB GDDR5
CPU: AMD PhenomII Six-core x 2.8Ghz
OS: 64 bit Win10 Pro
RAM: 20GB DDR3-1333: 2x8GB Mushkin, 1x4GB Kingston
HD: WD 2TB SATA [6GB/Sec]
PSU: Thermaltake TR2 600W ATX
Mob: Asus M5A97 ATX AM3+
Screens: 1x24" Philips 1080p LED + 1x23.6" Samsung 4K LED
Cooling: Corsair Hydro liquid-cooling
Case: Generic mid-ATX

**Comment by pupi1985** [comment]
Hi, thanks for the detailed bug report. However, you're missing the most important thing which is the exact command you're running. I tested `curl` in linux and it worked fine.

I think your issue might be here:
> Add the 'curl' command followed by the endpoint URL given by your DNS solution

Have you split the command in subsequent lines?
```
curl
https://google.com
```

**Comment by Ayelis** [comment]
Hi, thanks for the response!
I've tried it on multiple lines, even adding the path.
`C:\Windows\System32\curl`
`http://sync.afraid.org/u/capAGVaaZEJZKjt94wfZUf9q/`

I get "An error has been detected while executing command
C:\Windows\System32\curl
http://sync.afraid.org/u/capAGVaaZEJZKjt94wfZUf9q/"

I've tried curl.exe and curl without the filesystem path, and curl with the url on the same line, and the url without the trailing slash, and even changing the url to http://www.google.com. Always the same error. Command output always shows an empty box.

**Comment by Ayelis** [comment]
![WIN_20190613_22_55_15_Pro](https://user-images.githubusercontent.com/7215060/59486519-62e00880-8e2e-11e9-9ad4-965e5f57322a.jpg)
Same thing with http or https...
![WIN_20190613_22_58_38_Pro](https://user-images.githubusercontent.com/7215060/59486635-d08c3480-8e2e-11e9-9af7-2bfd057a8040.jpg)

**Comment by pupi1985** [comment]
Hmm... OK. I think I will be able to try it out tomorrow in a Windows PC. Is `curl` now part of Windows or where have you downloaded that executable from?

Random additional pointers:
- The error might be related to parsing the command rather than executing it (that's why the output is empty)
- Maybe the slashes or colons should be escaped (e.g.: `https:\/\/google.com`)

**Comment by Ayelis** [comment]
I've just tried escaping the slashes, and escaping the colon. Same errors. I've got nothing.

Curl has been a part of Windows 10 since December 2017, build 17063. Clicking properties on the executable gives me a file version 7.55.1.0, with copyright 1996-2017 to Daniel Stenberg, who I guess created curl in the first place. [His blog](https://daniel.haxx.se/blog/2018/01/13/microsoft-curls-too/) features the full story.

**Comment by pupi1985** [comment]
Just tested it. It is working fine. Like in the previous 12 years :D

Maybe it is a firewall issue.

**Comment by Ayelis** [comment]
That would certainly solve my problem, but it won't solve the problem with the app giving mixed messages. No text appearing in the error box makes me feel like there's no error, but I was just told something went wrong. So I thought I'd elevate this.
Thank you! :+1:

**Comment by pupi1985** [comment]
The error box is empty because it is not an error box. It is just the output of the command that it hasn't been able to run. In your case, it is empty, but probably in other platforms, with other executable, with other issues, it might be a different scenario.

I'll take a look at that in a future release, anyway.
