### ISSUE TITLE
Remove time interval

### ISSUE THREAD

**Issue by turret001** [pupi1985/IPMonitor#4]
why is there a time interval for checking? is it possible to get rid of it?

+does it send a new mail in every 10 minutes, regardless if the IP changed or not, or does it checks if the IP has changed and sends than

**Comment by pupi1985** [comment]
These are the reasons:
 * Most servers that most users will be frequently hitting won't like anyone to be performing automatic requests every second. In fact, DynDNS.org said they will blacklist any IP hitting their checkip page in intervals smaller than 10 minutes.
 * If a user really has de **need** to receive an update in less than 10 minutes, then most likely they also **need** an more *enterprise* tool than this one
 * Code is public so anyone can change it

> +does it send a new mail in every 10 minutes, regardless if the IP changed or not, or does it checks if the IP has changed and sends than

If you use the app you will answer that question on your own in 10 minutes top :) The app only notifies of IP changes not checks.

**Comment by turret001** [comment]
yep, seems like it. thanks for the answer. by the way, instead of getting the new IP, I get a text in mail saying [NEW_IP_HERE]. why would that be

**Comment by pupi1985** [comment]
Because you're testing sending the email. If you test it you only have your current IP address and there is no real new IP address. So it is just a placeholder.

**Comment by turret001** [comment]
oh I see, thank you once again.

**Comment by tyroafsal** [comment]
Thank you. So i have to wait until new ip comes.
