### ISSUE TITLE
How to setup command notification.

### ISSUE THREAD

**Issue by numanzahid** [pupi1985/IPMonitor#6]
Hi @pupi1985 
First I want to thank you for this awesome script. It helped me a lot during my trip.
I have a question if you can spare little time.
I am using IPMonitor on windows to get my dynamic ip address. previously I was using email notification. which works fine.
now I want to use it with [pushbullet-cli](https://github.com/GustavoKatel/pushbullet-cli).
pushbullet-cli is working fine and I am able to send messages with this via cmd, but I am not able to setup command notification for it in IPMonitor. There is not clear guide line on how to setup commands.
every time I test a command it gives the error: An error has been detected while executing the command.
can you give me and example on how to execute a simple command.
for example I want it to run: pb push -d 0 "%NEWIP%"
what exactly should I write in the text area?
will be waiting for your valued replay. thanks in advance.

**Comment by pupi1985** [comment]
Hi there.
Indeed there was an issue in Windows. As I use Linux it is very hard for me to spot those ones. I've created a new release. Could you please retest it and tell me if it works? BTW, I guess you will have to run this (or maybe the full path to `pb`):
```
pb
push
-d
0 
%NEWIP%
```
Also check this, please: https://github.com/pupi1985/IPMonitor/wiki/Command-line-examples

**Comment by numanzahid** [comment]
Hi @pupi1985 
Thanks for the update. Updated to 0.05.1. the command is working really fine now.
Thanks again for solving the problem.
