### ISSUE TITLE
How do you install and execute IPMonitor?

### ISSUE THREAD

**Issue by argus33** [pupi1985/IPMonitor#7]
i know i am a complete newbie to this.  i don't know how to install stuff unless it is in the repo's of ubuntu.  so i am using ubuntu 16.04 and every time i go to try to install things like this it is always a failure that is due to my part.  So i am asking my fellow Unix folks for some help. just point me in the right direction with some stuff so i can educate my self on installing things. i really want this program.

**Comment by pupi1985** [comment]
I don't use Ubuntu but I guess you just have to install Java 7 or 8. Then, download the tar.gz file, uncompress it wherever you want and that's it. As you can see, there is no installation process as it is a portable application :)

**Comment by argus33** [comment]
I have done what you say but there has to be something you run or click on to get it do do something.  What do you do after you extract it. Is there a set of commands you do. I have got it to do something on command line but have no idea what things do no instructions. I'm not a programmer I don't know Unix real well but have been playing with it for some 15 years. Things just work for me but I don't know how to make Unix/Ubuntu do everything I want it to do.  Is there supposed to be a gui in Unix platform?  Thank you for responding and helping.

**Comment by pupi1985** [comment]
Well, you asked me how to **install** but you actually meant how to **execute** it. Again, that depends even more on your operating system. Assuming you already have Java installed, if Ubuntu is a moderately decent operating system it will most likely run the IPMonitor.jar file with a double click on it. If it doesn't you should get a couple of options by right clicking on it.

Worst case scenario you could open a command a prompt in the directory where the IPMonitor.jar file resides and execute the command `java -jar IPMonitor.jar` and that should also execute it.

You could also Google something like _How to execute .jar files in Ubuntu_. There should be plenty of documentation.

**Comment by argus33** [comment]
Thank you for pointing me in the right direction. That's what I needed. I appreciate your help. Thank you for taking the time to program such a useful tool.

**Comment by pupi1985** [comment]
Welcome. Thanks to you too.
