### ISSUE TITLE
Unable to send email notifications

### ISSUE THREAD

**Issue by ashleyabye** [pupi1985/IPMonitor#8]
Hi there,

First I'd like to say thanks for the tool!

It would seem however that I'm having some issue with setting up the email notification system though.

When I use gmail's smtp sever with an account with lower security connections enabled, with ssl I get:
```
DEBUG: setDebug: JavaMail version 1.5.5
DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtps,com.sun.mail.smtp.SMTPSSLTransport,Oracle]
DEBUG SMTP: need username and password for authentication
DEBUG SMTP: useEhlo true, useAuth true
DEBUG SMTP: trying to connect to host "smtp.gmail.com", port 465, isSSL true
```

An error has been detected while trying to send the email.
Check the network settings and the email notification configuration.

Without ssl I get:
```
DEBUG: setDebug: JavaMail version 1.5.5
DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
DEBUG SMTP: need username and password for authentication
DEBUG SMTP: useEhlo true, useAuth true
DEBUG SMTP: trying to connect to host "smtp.gmail.com", port 587, isSSL false
220 smtp.gmail.com ESMTP y99sm14352133wmh.1 - gsmtp
DEBUG SMTP: connected to host "smtp.gmail.com", port: 587

EHLO Screenbox.home
250-smtp.gmail.com at your service, [109.152.144.2]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250 SMTPUTF8
DEBUG SMTP: Found extension "SIZE", arg "35882577"
DEBUG SMTP: Found extension "8BITMIME", arg ""
DEBUG SMTP: Found extension "STARTTLS", arg ""
DEBUG SMTP: Found extension "ENHANCEDSTATUSCODES", arg ""
DEBUG SMTP: Found extension "PIPELINING", arg ""
DEBUG SMTP: Found extension "SMTPUTF8", arg ""
DEBUG SMTP: use8bit false
MAIL FROM:<remoteaccessnotifier@gmail.com>
530 5.7.0 Must issue a STARTTLS command first. y99sm14352133wmh.1 - gsmtp
DEBUG SMTP: got response code 530, with response: 530 5.7.0 Must issue a STARTTLS command first. y99sm14352133wmh.1 - gsmtp

RSET
250 2.1.5 Flushed y99sm14352133wmh.1 - gsmtp
DEBUG SMTP: MessagingException while sending, THROW: 
com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.0 Must issue a STARTTLS command first. y99sm14352133wmh.1 - gsmtp
```

Is there something I've configured correctly? From what I could tell I thought I'd followed the connection settings right.

Any time you can spare to take a look would be appreciated!

**Comment by pupi1985** [comment]
Hi,

In the screenshots in the wiki I've added an example on how the email settings should be completed for GMail. That configuration is working for me. If it doesn't for you, the issue is not related to IP Monitor.

Note that there can be so many issues related to sending emails that it makes no point for me to dig very deep on that. It could be that you have not configured properly GMail, your antivirus could be blocking the port, your ISP could be blocking you from sending emails, etc.

**Comment by ashleyabye** [comment]
Fair enough man, thanks for replying anyway :)

I'll try forwarding the smtp port to the machine and see if that makes a difference. Failing that I'll try using my work's smtp and see if that does it.

Thanks for the fast response!
